sonar.projectKey=gigabit-clowns_rexlib-python
sonar.organization=gigabit-clowns
sonar.sources=src, python, .github
sonar.tests=tests
sonar.exclusions=doc/**
sonar.coverage.exclusions=src/**
sonar.issue.ignore.multicriteria=pybind_operators
sonar.issue.ignore.multicriteria.pybind_operators.ruleKey=cpp:S1764
sonar.issue.ignore.multicriteria.pybind_operators.resourceKey=src/**
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.python.coverage.reportPaths=coverage.xml
