sonar.projectKey=gigabit-clowns_rexlib-python
sonar.organization=gigabit-clowns
sonar.sources=src, python, .github
sonar.tests=tests
sonar.exclusions=doc/**
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.python.coverage.reportPaths=coverage.xml
