from __future__ import annotations
import typing
from . import dispatch
from . import functional
from . import hardware
from . import ndarray
from . import numerical
__all__: list[str] = ['Plugin', 'PluginManager', 'ServiceCatalog', 'Version', 'dispatch', 'functional', 'get_default_plugin_directory', 'get_plugin_directory', 'hardware', 'ndarray', 'numerical']
class Plugin:
    def __repr__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def version(self) -> Version:
        ...
class PluginManager:
    def __init__(self) -> None:
        ...
    def add_plugin(self, plugin: Plugin) -> None:
        ...
    def discover_plugins(self, directory: str | None = None) -> None:
        ...
    def load_plugin(self, path: str) -> Plugin:
        ...
    @property
    def plugins(self) -> list:
        ...
class ServiceCatalog:
    def __init__(self, register_builtin_backends: bool = True) -> None:
        ...
    def register_plugins(self, arg0: PluginManager) -> int:
        ...
class Version:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Version) -> bool:
        ...
    def __ge__(self, arg0: Version) -> bool:
        ...
    def __getstate__(self) -> tuple[int, int, int]:
        ...
    def __gt__(self, arg0: Version) -> bool:
        ...
    def __init__(self, major: int, minor: int, patch: int) -> None:
        ...
    def __le__(self, arg0: Version) -> bool:
        ...
    def __lt__(self, arg0: Version) -> bool:
        ...
    def __ne__(self, arg0: Version) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def major(self) -> int:
        ...
    @major.setter
    def major(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def minor(self) -> int:
        ...
    @minor.setter
    def minor(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def patch(self) -> int:
        ...
    @patch.setter
    def patch(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
def get_default_plugin_directory() -> str:
    ...
def get_plugin_directory() -> str:
    ...
__version__: str = '0.1.0'
