from __future__ import annotations
import typing
import xmipp4._core_binding.dispatch
import xmipp4._core_binding.hardware
import xmipp4._core_binding.ndarray
import xmipp4._core_binding.numerical
__all__: list[str] = ['abs', 'add', 'cast', 'cast_copy', 'copy', 'divide', 'empty', 'fill', 'full', 'modulo', 'multiply', 'negate', 'ones', 'subtract', 'to_device', 'to_device_copy', 'to_host', 'to_host_copy', 'transfer', 'transfer_copy', 'zeros']
def abs(x: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def add(x: xmipp4._core_binding.ndarray.Array, y: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def cast(input: xmipp4._core_binding.ndarray.Array, target_type: xmipp4._core_binding.numerical.NumericalType, context: xmipp4._core_binding.dispatch.ExecutionContext) -> xmipp4._core_binding.ndarray.Array:
    ...
def cast_copy(input: xmipp4._core_binding.ndarray.Array, target_type: xmipp4._core_binding.numerical.NumericalType, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def copy(source: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def divide(x: xmipp4._core_binding.ndarray.Array, y: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def empty(descriptor: xmipp4._core_binding.ndarray.ArrayDescriptor, affinity: xmipp4._core_binding.hardware.MemoryResourceAffinity, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def fill(out: xmipp4._core_binding.ndarray.Array, fill_value: typing.Any, context: xmipp4._core_binding.dispatch.ExecutionContext) -> None:
    ...
def full(descriptor: xmipp4._core_binding.ndarray.ArrayDescriptor, affinity: xmipp4._core_binding.hardware.MemoryResourceAffinity, fill_value: typing.Any, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def modulo(x: xmipp4._core_binding.ndarray.Array, y: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def multiply(x: xmipp4._core_binding.ndarray.Array, y: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def negate(x: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def ones(descriptor: xmipp4._core_binding.ndarray.ArrayDescriptor, affinity: xmipp4._core_binding.hardware.MemoryResourceAffinity, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def subtract(x: xmipp4._core_binding.ndarray.Array, y: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def to_device(input: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext) -> xmipp4._core_binding.ndarray.Array:
    ...
def to_device_copy(input: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def to_host(input: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext) -> xmipp4._core_binding.ndarray.Array:
    ...
def to_host_copy(input: xmipp4._core_binding.ndarray.Array, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def transfer(input: xmipp4._core_binding.ndarray.Array, affinity: xmipp4._core_binding.hardware.MemoryResourceAffinity, context: xmipp4._core_binding.dispatch.ExecutionContext) -> xmipp4._core_binding.ndarray.Array:
    ...
def transfer_copy(input: xmipp4._core_binding.ndarray.Array, affinity: xmipp4._core_binding.hardware.MemoryResourceAffinity, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
def zeros(descriptor: xmipp4._core_binding.ndarray.ArrayDescriptor, affinity: xmipp4._core_binding.hardware.MemoryResourceAffinity, context: xmipp4._core_binding.dispatch.ExecutionContext, out: xmipp4._core_binding.ndarray.Array | None = None) -> xmipp4._core_binding.ndarray.Array:
    ...
