from __future__ import annotations
import collections.abc
import typing
import xmipp4._core_binding.numerical
__all__: list[str] = ['Array', 'ArrayDescriptor', 'is_initialized', 'make_contiguous_array_descriptor']
class Array:
    def __abs__(self) -> Array:
        ...
    def __add__(self, other: Array) -> Array:
        ...
    def __copy__(self) -> Array:
        ...
    def __deepcopy__(self, memo: dict) -> Array:
        ...
    def __iadd__(self, other: Array) -> Array:
        ...
    def __imod__(self, other: Array) -> Array:
        ...
    def __imul__(self, other: Array) -> Array:
        ...
    def __isub__(self, other: Array) -> Array:
        ...
    def __itruediv__(self, other: Array) -> Array:
        ...
    def __mod__(self, other: Array) -> Array:
        ...
    def __mul__(self, other: Array) -> Array:
        ...
    def __neg__(self) -> Array:
        ...
    def __pos__(self) -> Array:
        ...
    def __sub__(self, other: Array) -> Array:
        ...
    def __truediv__(self, other: Array) -> Array:
        ...
class ArrayDescriptor:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: ArrayDescriptor) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: ArrayDescriptor) -> bool:
        ...
    @property
    def data_type(self) -> xmipp4._core_binding.numerical.NumericalType:
        ...
def is_initialized(arg0: ArrayDescriptor) -> bool:
    ...
def make_contiguous_array_descriptor(extents: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], data_type: xmipp4._core_binding.numerical.NumericalType) -> ArrayDescriptor:
    ...
