#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only

"""
Generate the type stubs for the compiled extension.

Runs pybind11-stubgen against an installed copy of the package and marks
every stub as generated. Invoked from CMake during the build, and usable
by hand against a development install.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile

HEADER = (
	"# Generated by scripts/generate_stubs.py. Do not edit.\n"
	"# Regenerated whenever the bindings are built.\n"
)

def parse_arguments() -> argparse.Namespace:
	"""Read the module to document, where to find it and where to write."""
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--module", required=True)
	parser.add_argument(
		"--search-path",
		required=True,
		help="Directory holding the importable package.",
	)
	parser.add_argument(
		"--output",
		required=True,
		help="Directory the stubs are written to, replacing its contents.",
	)
	return parser.parse_args()

def run_stubgen(module: str, search_path: str, destination: str) -> None:
	"""Run pybind11-stubgen with the package importable from search_path."""
	environment = dict(os.environ)
	environment["PYTHONPATH"] = os.pathsep.join(
		[search_path, environment.get("PYTHONPATH", "")]
	).rstrip(os.pathsep)
	subprocess.run(
		[sys.executable, "-m", "pybind11_stubgen", module, "-o", destination],
		env=environment,
		check=True,
	)

def mark_as_generated(directory: pathlib.Path) -> None:
	"""Prepend the generated-file notice to every stub."""
	for stub in sorted(directory.rglob("*.pyi")):
		stub.write_text(
			HEADER + stub.read_text(encoding="utf-8"), encoding="utf-8"
		)

def main() -> None:
	"""Generate the stubs and move them into place."""
	arguments = parse_arguments()
	output = pathlib.Path(arguments.output)

	with tempfile.TemporaryDirectory() as staging:
		run_stubgen(arguments.module, arguments.search_path, staging)

		# pybind11-stubgen mirrors the module path, so xmipp4._core_binding
		# lands in xmipp4/_core_binding.
		generated = pathlib.Path(staging).joinpath(
			*arguments.module.split(".")
		)
		if not generated.is_dir():
			raise SystemExit(f"pybind11-stubgen wrote nothing to {generated}")

		mark_as_generated(generated)

		if output.exists():
			shutil.rmtree(output)
		output.parent.mkdir(parents=True, exist_ok=True)
		shutil.move(str(generated), str(output))

	print(f"Stubs written to {output}")

if __name__ == "__main__":
	main()
