#!/bin/bash

[[ "${DEBUG}" == 'true' ]] && set -o xtrace

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"
ROOT_DIR="$CURRENT_DIR/.."

pushd "${ROOT_DIR}" > /dev/null

    echo "Generating .pyi stubs for xmipp4._core_binding..."
    OUT_DIR="$(mktemp -d)"
    python -m pybind11_stubgen xmipp4._core_binding -o "${OUT_DIR}"
    STUBGEN_EXIT_CODE=$?
    if [ $STUBGEN_EXIT_CODE -ne 0 ]; then
        rm -rf "${OUT_DIR}"
        exit $STUBGEN_EXIT_CODE
    fi

    # Say out loud that these are not hand-written, since they are committed
    # next to the sources they describe.
    for STUB in "${OUT_DIR}"/xmipp4/_core_binding/*.pyi; do
        {
            echo "# Generated by scripts/generate-stubs.sh. Do not edit."
            echo "# Regenerate after changing the bindings; CI rejects stale stubs."
            cat "${STUB}"
        } > "${STUB}.new"
        mv "${STUB}.new" "${STUB}"
    done

    rm -rf python/xmipp4/_core_binding
    cp -r "${OUT_DIR}/xmipp4/_core_binding" python/xmipp4/_core_binding
    rm -rf "${OUT_DIR}"

    echo "Stubs written to python/xmipp4/_core_binding/"

popd > /dev/null
