name: Keep caches warm

permissions: {}

on:
  schedule:
    - cron: '17 5 * * *'

  pull_request:
    paths:
      - '.github/workflows/keep-caches-warm.yml'

  workflow_dispatch:

concurrency:
  group: keep-caches-warm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  touch:
    name: Touch ${{ matrix.prefix }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - prefix: wheels-ubuntu-latest-x86_64
            path: /tmp/ccache
          - prefix: wheels-ubuntu-24.04-arm-aarch64
            path: /tmp/ccache
          - prefix: ccache-ubuntu-latest-g++
            path: ${{ github.workspace }}/.ccache
          - prefix: ccache-pip-ubuntu-latest
            path: ${{ github.workspace }}/.ccache
    steps:
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ matrix.path }}
          key: ${{ matrix.prefix }}-none
          restore-keys: ${{ matrix.prefix }}-
          lookup-only: true
